source <(fzf --zsh)

export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init zsh)"

alias proj="cd ~/personal"
alias vim="nvim"

alias l="eza --long --all"
alias ls="eza"
alias la="eza --all"
alias ll="eza --long"

alias hmsi="home-manager switch --impure --flake"
alias drsi="darwin-rebuild switch --impure --flake"
