accordion-padding = 0

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.right = 0
outer.bottom = 0
outer.top = 0

[mode.main.binding]
f12 = "mode z"

[mode.z.binding]
e = [ "exec-and-forget open -a Alacritty", "mode main" ]
r = "mode raycast"
o = "mode open_apps"
f = "mode fbrowsers"
esc = "mode main"

[mode.raycast.binding]
a = [ "exec-and-forget open raycast://extensions/raycast/system/toggle-system-appearance", "mode main" ]
esc = "mode main"

[mode.open_apps.binding]
m = [ "exec-and-forget open -a Messages", "mode main" ]
v = [ "exec-and-forget open -a SurfShark", "mode main" ]
s = [ "exec-and-forget open -a Spotify", "mode main" ]
n = [ "exec-and-forget open -a Notes", "mode main" ]
d = [ "exec-and-forget open -a Digiexam", "mode main" ]
esc = "mode main"

[mode.fbrowsers.binding]
s = [ "exec-and-forget open -a Safari", "mode main" ]
g = [ "exec-and-forget open -a 'Google Chrome'", "mode main" ]
esc = "mode main"
