[font]
# normal = { family = "Menlo" }
normal = { family = "Hack Nerd Font Mono" }
# normal = { family = "Iosevka Nerd Font Mono" }
size = 20.5

[window]
title = "Alacritty"
dynamic_title = false
startup_mode = "Maximized"
# opacity = 0.7
# blur = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
