[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold blue"

[git_branch]
symbol = ""
style = "bold purple"

[git_status]
style = "bold red"

[cmd_duration]
disabled = true

[line_break]
disabled = true

