
format = '\[$time\]-\[$username\]-\[$hostname\]-\[$directory\]-\[$status\]-\[$git_branch\]-\[$git_status\]-$line_break $character'
add_newline = true

palette = 'alacritty'

[palettes.alacritty]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

bright-black = "#6b6b6b"
bright-red = "#c55555"
bright-green = "#aac474"
bright-yellow =  "#feca88"
bright-blue = "#82b8c8"
bright-magenta = "#c28cb8"
bright-cyan = "#93d3c3"
bright-white = "#f8f8f8"

dim-black = "#0f0f0f"
dim-red = "#712b2b"
dim-green = "#5f6f3a"
dim-yellow = "#a17e4d"
dim-blue = "#456877"
dim-blue2 = "#5381a6"
dim-magenta = "#704d68"
dim-cyan = "#4d7770"
dim-white = "#8e8e8e"

[time]
disabled = false
format = "[$time](fg:bold cyan)"
time_format = "%H:%M"

[username]
show_always = true
format = "[$user](fg:bold magenta)"

[hostname]
ssh_only = false
format = "[$hostname](fg:bold green)"

[directory]
truncation_length = 3
truncate_to_repo = false
format = "[$path](fg:bold dim-blue2)"

[shell]
disabled = false
format = "[zsh](bold white)"

[status]
disabled = false
format = '[$status]($style)'
map_symbol = true
success_symbol = '0' 
symbol = ''  
success_style = 'green' 
failure_style = 'red'  

[git_branch]
symbol = ""
format = '[$branch(:$branch)](fg:bold white)'

[git_status]
format = '[$all_status](fg:bold yellow)'

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
# ➜

[line_break]
disabled = false

# [character]
# success_symbol = "[➜](bold green)"
# error_symbol = "[➜](bold red)"
#
# [directory]
# truncation_length = 3
# truncate_to_repo = false
# style = "bold blue"
#
# [git_branch]
# symbol = ""
# style = "bold purple"
#
# [git_status]
# style = "bold red"
#
# [cmd_duration]
# disabled = true
#
# [line_break]
# disabled = true
#
