[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font]
size = 24

[window]
title = "Alacritty"
dynamic_title = false

[colors.primary]
# background = "#131313"
background = "#000000"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
