source <(fzf --zsh)

# PROMPT='%F{#44a64f}%n@%m%f:%F{blue}%~%f$ '

PROMPT='%F{#20536d}%n%F{#460854}@%F{#98c5a0}%m%F{#DEDEDE}:%F{#5777a1}%~%f %F{#4bc287}$ %F{#DEDEDE}'

alias proj="cd ~/personal"
alias vim="nvim"

alias l="eza --long --all"
alias ls="eza"
alias la="eza --all"
alias ll="eza --long"

alias drs="darwin-rebuild switch --flake"

export EDITOR=nvim
export VISUAL=nvim
