source <(fzf --zsh)

PROMPT='%F{#44a64f}%n@%m%f:%F{blue}%~%f$ '

alias proj="cd ~/personal"
alias vim="nvim"

alias l="eza --long --all"
alias ls="eza"
alias la="eza --all"
alias ll="eza --long"

alias drs="darwin-rebuild switch --flake"

export EDITOR=nvim
export VISUAL=nvim
